-- SIKANDA V1 Secure — migrasi Supabase idempoten
-- WAJIB: buat backup database sebelum menjalankan berkas ini.

begin;

alter table if exists public.pegawai
  add column if not exists kategori_pppk text,
  add column if not exists is_active boolean not null default true,
  add column if not exists updated_at timestamptz,
  add column if not exists updated_by text;

alter table if exists public.assets_vehicle
  add column if not exists is_active boolean not null default true,
  add column if not exists updated_at timestamptz,
  add column if not exists updated_by text;

alter table if exists public.assets_equipment
  add column if not exists is_active boolean not null default true,
  add column if not exists updated_at timestamptz,
  add column if not exists updated_by text;

alter table if exists public.app_access
  add column if not exists email text,
  add column if not exists role text not null default 'pegawai',
  add column if not exists nama text,
  add column if not exists nip text,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_by text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists last_login timestamptz;

alter table if exists public.system_config
  add column if not exists key text,
  add column if not exists value text,
  add column if not exists updated_at timestamptz;

create unique index if not exists system_config_key_uidx
  on public.system_config (key);

create unique index if not exists app_access_email_uidx
  on public.app_access (email);

update public.app_access
set role = 'admin'
where lower(trim(role)) in ('administrator', 'super_admin', 'super admin');

insert into public.system_config (key, value, updated_at) values
  ('KGB_CYCLE_YEARS', '2', now()),
  ('PANGKAT_CYCLE_YEARS', '4', now()),
  ('BUP_USIA', '58', now()),
  ('NOTIF_WINDOW_HARI', '180', now()),
  ('NOTIF_COOLDOWN_DAYS', '1', now())
on conflict (key) do nothing;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_email text not null,
  actor_role text not null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb
);

alter table public.audit_logs
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists actor_email text,
  add column if not exists actor_role text,
  add column if not exists action text,
  add column if not exists entity_type text,
  add column if not exists entity_id text,
  add column if not exists details jsonb not null default '{}'::jsonb;

create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);
create index if not exists audit_logs_actor_email_idx on public.audit_logs (actor_email);
create index if not exists pegawai_active_nip_idx on public.pegawai (is_active, nip);
create index if not exists assets_vehicle_active_id_idx on public.assets_vehicle (is_active, asset_id);
create index if not exists assets_equipment_active_id_idx on public.assets_equipment (is_active, asset_id);
create index if not exists app_access_active_email_idx on public.app_access (is_active, email);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'pegawai_kategori_pppk_check'
      and conrelid = 'public.pegawai'::regclass
  ) then
    alter table public.pegawai add constraint pegawai_kategori_pppk_check
      check (kategori_pppk is null or kategori_pppk in ('penuh_waktu', 'paruh_waktu'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'app_access_role_check'
      and conrelid = 'public.app_access'::regclass
  ) then
    alter table public.app_access add constraint app_access_role_check
      check (lower(role) in ('admin', 'pimpinan', 'pegawai'));
  end if;
end $$;

-- Seluruh akses aplikasi V1 melewati Apps Script dengan service role. Tidak ada
-- tabel yang boleh dibaca langsung oleh browser menggunakan anon/authenticated.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'pegawai','assets_vehicle','assets_equipment','asset_locations','system_config',
    'app_access','audit_logs','assets_inventory','vehicle_budget','maintenance','loans'
  ] loop
    if to_regclass('public.' || table_name) is not null then
      execute format('alter table public.%I enable row level security', table_name);
      execute format('revoke all on table public.%I from anon, authenticated', table_name);
      execute format('grant all on table public.%I to service_role', table_name);
    end if;
  end loop;
end $$;

grant usage on schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;

-- Pemeriksaan setelah migrasi:
-- select key, value from public.system_config order by key;
-- select tablename, rowsecurity from pg_tables where schemaname='public';
