-- ===========================================================================
-- ⚠️ FILE LEGACY — JANGAN DIPAKAI DI PRODUKSI
-- ===========================================================================
-- File ini dulu mematikan RLS total selama masa pengembangan awal.
-- Sejak migrasi total ke Supabase, gunakan `supabase_rls.sql` yang
-- MENGAKTIFKAN RLS dengan kebijakan eksplisit per tabel.
-- Dipertahankan hanya sebagai arsip; isi perintah dinonaktifkan.
-- ===========================================================================
-- ALTER TABLE public.pegawai DISABLE ROW LEVEL SECURITY;            -- (legacy)
-- ALTER TABLE public.assets_vehicle DISABLE ROW LEVEL SECURITY;     -- (legacy)
-- ALTER TABLE public.assets_equipment DISABLE ROW LEVEL SECURITY;   -- (legacy)
-- ALTER TABLE public.assets_inventory DISABLE ROW LEVEL SECURITY;   -- (legacy)
-- ALTER TABLE public.vehicle_budget DISABLE ROW LEVEL SECURITY;     -- (legacy)
-- ALTER TABLE public.maintenance DISABLE ROW LEVEL SECURITY;        -- (legacy)
-- ALTER TABLE public.loans DISABLE ROW LEVEL SECURITY;              -- (legacy)
-- ALTER TABLE public.asset_locations DISABLE ROW LEVEL SECURITY;    -- (legacy)
-- ALTER TABLE public.system_config DISABLE ROW LEVEL SECURITY;      -- (legacy)
